### PR TITLE
Fixes #2

### LINKED ISSUE #2: Stripper breaks '\n' in entities.
There are a few zombie escape maps which make use of newlines in game_text entities like this:

```
entity
{
    "id" "2708531"
    "origin" "-13026 14610 8"
    "y" ".3"
    "x" ".05"
    "targetname" "Knife_Frost_HudHint"
    "spawnflags" "0"
    "message" "Name: Frost Magick 
Description: Ice Age ! 
Effect: Slow Humans 
Duration: 4 Secs 
Cooldown: 90 Secs"
    "holdtime" "7"
    "fxtime" "0.5"
    "fadeout" "2"
    "fadein" ".02"
    "effect" "2"
    "color2" "128 255 255"
    "color" "0 255 255"
    "channel" "4"
    "classname" "game_text"
}
```

If stripper is loaded the message will either not work at all or cut off after the first newline.

I was trying to fix this myself but it seems like I am unable to compile stripper, since there are also no instructions on how to do so.
I made a build directory, changed the paths in the AMBuildScript to reflect the real paths of the sdk, ran CC=gcc CXX=gcc python3 ../configure.py --enable-optimize and then python3 build.py
It seemed to compile a few things and create the package with all the correct files.
Yet stripper wouldn't load with the following error message: Failed to load plugin addons/stripper/bin/stripper_mm (Could not find LoadStripper function).

### PR DESCRIPTION
**Pull request by BotoX**
(Newlines in entity properties not working)
See issue #2

### CODE REVIEW

File: parser.cpp [hunk 1]
```diff
@@ -159,9 +159,13 @@ void Stripper::SetEntityList(const char *ents)
     char *_tmp = NULL;
     size_t _tmpsize = 0;
     size_t pos = 0;
+    char in_string = 0;
```
Comment (WildCard65) [inline parser.cpp:162]: Would this be better as a bool?

Comment (BotoX) [inline parser.cpp:162]: I guess it'd make more sense, yeah. I used char because bool is not a native C type. (https://stackoverflow.com/questions/1608318/is-bool-a-native-c-type)

Though I guess doing in_string ^= true; would look kinda weird whereas with 0 and 1 it makes more sense :p 
(I used char because it is just "one byte", it's not used as a character in this context)

Comment (WildCard65) [inline parser.cpp:162]: As far as I'm aware, all MM:S plugins are c++

Comment (BotoX) [inline parser.cpp:162]: Yeah, I think I just looked at the other lines and felt like I am in a C environment if that makes sense.
I could change it to bool and ^= true but I don't think it matters tbh. looking at the rest of the code, there is no clear convention and it looks like a C program with C++ thrown in.

My only fear is that there is some case where this will break on some map though it's been running fine on the GFL Zombie Escape server for the past few days.

I am still wondering how to make a functional build with ambuild, I used the makefile to build the stripper.core.so, when I used ambuild the stripper.16.css.so wouldn't load (see #2 Could not find LoadStripper function)
